---
#db
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/familyHealthKeeper
    data-username: savand
  data:
    rest:
      basePath: /api