---
#db
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/familyHealthKeeper
    username: savand
  data:
    rest:
      basePath: /api
      
  mvc:
    view:
      prefix: /WEB-INF/view/jsp/
      suffix: .jsp